// FILE: ./js/app/main.js

// Central browser entry for Code-Command. Loads WASM engine, Monaco editor,
// file tree, and output panel, wiring UI events to the CC-API. [file:2]

import initWasm, * as CCEngine from "../lib/wasm/cc_engine.js";
import { createEditor } from "./editor/monaco-loader.js";
import { FileTree } from "./editor/file-tree.js";
import { OutputPanel } from "./terminal/output-panel.js";
import * as GithubAPI from "./github/api.js";

let editor = null;
let fileTree = null;
let outputPanel = null;
let currentRepo = null;

// WASM initialization state. [file:2]
let wasmReady = false;

/**
 * Initialize the CC-Engine WASM module and UI components.
 * This runs once on page load and does not perform any setup beyond
 * fetching static assets, satisfying CC-ZERO. [file:2]
 */
async function bootstrap() {
  try {
    outputPanel = new OutputPanel(
      document.getElementById("cc-terminal-output")
    );

    outputPanel.logInfo("Initializing Code-Command engine…");

    // Initialize WASM from generated glue; this fetches cc-engine.wasm. [file:2]
    await initWasm();
    wasmReady = true;

    const editorContainer = document.getElementById("cc-editor");
    editor = await createEditor(editorContainer, "// Code-Command ready.\n", "rust");

    const treeContainer = document.getElementById("cc-file-tree");
    fileTree = new FileTree(treeContainer, {
      onFileSelect: handleFileSelect,
    });

    wireControls();

    outputPanel.logOk("Engine and UI initialized.");
  } catch (err) {
    console.error(err);
    if (outputPanel) {
      outputPanel.logError("Failed to initialize Code-Command engine.");
    }
  }
}

/**
 * Wire header controls (Load Repo, Run Task) to their handlers. [file:2]
 */
function wireControls() {
  const loadButton = document.getElementById("cc-load-repo");
  const runTaskButton = document.getElementById("cc-run-task");
  const repoInput = document.getElementById("cc-repo-input");

  loadButton.addEventListener("click", async () => {
    const value = (repoInput.value || "").trim();
    if (!value) {
      outputPanel.logWarn("Enter owner/repo before loading.");
      return;
    }
    const [owner, repo] = value.split("/");
    if (!owner || !repo) {
      outputPanel.logError("Repository must be in the form owner/repo.");
      return;
    }
    await loadRepository(owner, repo);
  });

  runTaskButton.addEventListener("click", async () => {
    await runCurrentTask();
  });
}

/**
 * Loads a GitHub repository tree into the VFS and updates the file tree UI. [file:2]
 */
async function loadRepository(owner, repo) {
  if (!wasmReady) {
    outputPanel.logError("WASM engine not ready.");
    return;
  }

  try {
    outputPanel.logInfo(`Loading repo ${owner}/${repo}…`);

    const tree = await GithubAPI.fetchRepoTree(owner, repo);
    const vfsSnapshot = GithubAPI.treeToVfsSnapshot(tree);

    // Seed the WASM-side VFS. [file:2]
    CCEngine.cc_init_vfs(JSON.stringify(vfsSnapshot));

    // Update UI tree. [file:2]
    fileTree.setTree(tree);
    currentRepo = { owner, repo };

    outputPanel.logOk(`Repository loaded: ${owner}/${repo}`);
  } catch (err) {
    console.error(err);
    outputPanel.logError("Failed to load repository tree.");
  }
}

/**
 * Handles file selection from the FileTree component. [file:2]
 */
async function handleFileSelect(path) {
  if (!wasmReady) {
    outputPanel.logError("WASM engine not ready.");
    return;
  }

  try {
    outputPanel.logInfo(`Opening ${path}…`);

    // Ask WASM to read from VFS (which may call back to JS/GitHub). [file:2]
    const content = CCEngine.cc_read_file(path);
    if (editor) {
      const language = guessLanguageFromPath(path);
      editor.setValue(content || "");
      monaco.editor.setModelLanguage(editor.getModel(), language);
    }

    outputPanel.logOk(`Opened ${path}.`);
  } catch (err) {
    console.error(err);
    outputPanel.logError(`Failed to open ${path}.`);
  }
}

/**
 * Builds and executes a Single-Iteration Task Queue based on editor content.
 * In a typical AI-chat integration, the task JSON will be generated by the agent. [file:2]
 */
async function runCurrentTask() {
  if (!wasmReady) {
    outputPanel.logError("WASM engine not ready.");
    return;
  }
  if (!editor) {
    outputPanel.logError("Editor not initialized.");
    return;
  }

  const model = editor.getModel();
  if (!model) {
    outputPanel.logError("No active editor model.");
    return;
  }

  const path = fileTree.getActivePath() || "src/main.rs";
  const code = editor.getValue();

  // Minimal SITQ payload: create/update file, then validate with key tags. [file:2]
  const taskPayload = {
    tasks: [
      {
        kind: "update",
        path,
        content: code,
        sha: "",
        tags: [],
      },
      {
        kind: "validate",
        path,
        content: "",
        sha: "",
        tags: ["CC-FILE", "CC-FULL", "CC-LANG", "CC-PATH"],
      },
    ],
  };

  outputPanel.logInfo(`Running Single-Iteration Task Queue for ${path}…`);

  try {
    const reportJson = CCEngine.cc_execute_task(JSON.stringify(taskPayload));
    outputPanel.renderTaskReport(reportJson);
  } catch (err) {
    console.error(err);
    outputPanel.logError("Task execution failed.");
  }
}

/**
 * Heuristic language guesser based on file extension. [file:2]
 */
function guessLanguageFromPath(path) {
  const lower = path.toLowerCase();
  if (lower.endsWith(".rs")) return "rust";
  if (lower.endsWith(".js")) return "javascript";
  if (lower.endsWith(".cpp") || lower.endsWith(".cc") || lower.endsWith(".h")) {
    return "cpp";
  }
  if (lower.endsWith(".md") || lower.endsWith(".aln")) return "markdown";
  return "plaintext";
}

// Kick everything off on DOM ready. No setup scripts, no env vars, satisfying CC-ZERO. [file:2]
window.addEventListener("DOMContentLoaded", () => {
  bootstrap();
});
